#!/usr/bin/env python
"""
Replay combined digit motion data on SO101 robot.

This script replays the combined motion data generated by the digit_motion_agent.

Usage:
    python replay_combined_motion.py \
        --motion-dir /path/to/combined_number_18 \
        --robot-port /dev/tty.usbmodem58760431541

Examples:
    # Replay number 18
    python replay_combined_motion.py \
        --motion-dir ./shubhamt0802/combined_number_18 \
        --robot-port /dev/tty.usbmodem58760431541
"""

import json
import logging
import time
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

# LeRobot imports
try:
    from lerobot.robots import make_robot_from_config
    from lerobot.robots.so101_follower import SO101Follower, SO101FollowerConfig
    from lerobot.utils.robot_utils import precise_sleep
    from lerobot.utils.utils import init_logging, log_say
    LEROBOT_AVAILABLE = True
except ImportError:
    LEROBOT_AVAILABLE = False
    print("Warning: LeRobot not available. Running in simulation mode.")


@dataclass
class ReplayConfig:
    """Configuration for replay."""
    motion_dir: str | Path
    robot_port: str = "/dev/tty.usbmodem58760431541"
    robot_id: str = "digit_writer"
    play_sounds: bool = True
    simulate: bool = False


def load_combined_motion(motion_dir: Path) -> tuple[pd.DataFrame, dict]:
    """Load combined motion data from directory.
    
    Returns:
        Tuple of (actions DataFrame, info dict)
    """
    data_parquet = motion_dir / "data" / "chunk-000" / "file-000.parquet"
    info_json = motion_dir / "meta" / "info.json"
    
    if not data_parquet.exists():
        raise FileNotFoundError(f"Motion data not found: {data_parquet}")
    
    df = pd.read_parquet(data_parquet)
    
    with open(info_json) as f:
        info = json.load(f)
    
    return df, info


def replay_motion(cfg: ReplayConfig):
    """Replay combined motion on robot."""
    if LEROBOT_AVAILABLE:
        init_logging()
    
    motion_dir = Path(cfg.motion_dir)
    df, info = load_combined_motion(motion_dir)
    
    fps = info["fps"]
    number = info.get("number_produced", "unknown")
    total_frames = info["total_frames"]
    duration = total_frames / fps
    
    print(f"Loaded motion for number {number}")
    print(f"Total frames: {total_frames}, FPS: {fps}, Duration: {duration:.2f}s")
    
    # Get action column names from info
    action_names = info["features"]["action"]["names"]
    
    if cfg.simulate or not LEROBOT_AVAILABLE:
        # Simulation mode - just print the actions
        print("Running in SIMULATION mode")
        print(f"Simulating replay of number {number}")
        
        for idx in range(len(df)):
            start_t = time.perf_counter()
            
            # Extract action from array column
            action = {}
            action_data = df.iloc[idx]["action"]
            
            # Handle numpy array or list
            if hasattr(action_data, '__iter__') and not isinstance(action_data, str):
                for i, name in enumerate(action_names):
                    if i < len(action_data):
                        action[name] = float(action_data[i])
            
            if idx % 30 == 0:  # Print every second
                print(f"Frame {idx}/{total_frames}: {action}")
            
            dt_s = time.perf_counter() - start_t
            sleep_time = max(0, 1/fps - dt_s)
            if LEROBOT_AVAILABLE:
                precise_sleep(sleep_time)
            else:
                time.sleep(sleep_time)
        
        print("Simulation complete!")
        return
    
    # Real robot mode
    robot_config = SO101FollowerConfig(
        port=cfg.robot_port,
        id=cfg.robot_id
    )
    robot = SO101Follower(robot_config)
    
    try:
        robot.connect()
        log_say(f"Replaying number {number}", cfg.play_sounds, blocking=True)
        
        for idx in range(len(df)):
            start_t = time.perf_counter()
            
            # Extract action from array column
            action = {}
            action_data = df.iloc[idx]["action"]
            
            # Handle numpy array or list - convert to robot format
            if hasattr(action_data, '__iter__') and not isinstance(action_data, str):
                for i, name in enumerate(action_names):
                    if i < len(action_data):
                        # Robot expects keys like "shoulder_pan.pos"
                        action[name] = float(action_data[i])
            
            robot.send_action(action)
            
            dt_s = time.perf_counter() - start_t
            precise_sleep(max(0, 1 / fps - dt_s))
        
        log_say("Replay complete", cfg.play_sounds, blocking=True)
        
    finally:
        robot.disconnect()


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Replay combined digit motion")
    parser.add_argument(
        "--motion-dir",
        type=str,
        required=True,
        help="Directory containing combined motion data"
    )
    parser.add_argument(
        "--robot-port",
        type=str,
        default="/dev/tty.usbmodem58760431541",
        help="Robot USB port"
    )
    parser.add_argument(
        "--robot-id",
        type=str,
        default="digit_writer",
        help="Robot identifier"
    )
    parser.add_argument(
        "--simulate",
        action="store_true",
        help="Run in simulation mode (no robot)"
    )
    parser.add_argument(
        "--no-sound",
        action="store_true",
        help="Disable voice feedback"
    )
    
    args = parser.parse_args()
    
    config = ReplayConfig(
        motion_dir=args.motion_dir,
        robot_port=args.robot_port,
        robot_id=args.robot_id,
        simulate=args.simulate,
        play_sounds=not args.no_sound
    )
    
    replay_motion(config)


if __name__ == "__main__":
    main()

